language: cpp

os:
  - linux

sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
    packages:
      - gcc-4.9
      - gcc-5
      - clang-3.6
      - clang-3.8
      - valgrind

env:
  - CXX="g++-4.9" CXXFLAGS="-std=c++03"
  - CXX="g++-5"   CXXFLAGS="-std=c++03"
  - CXX="g++-4.9" CXXFLAGS="-std=c++11"
  - CXX="g++-5"   CXXFLAGS="-std=c++11"
  - CXX="clang++-3.6" CXXFLAGS="-std=c++03"
  - CXX="clang++-3.8" CXXFLAGS="-std=c++03"
  - CXX="clang++-3.6" CXXFLAGS="-std=c++11"
  - CXX="clang++-3.8" CXXFLAGS="-std=c++11"

before_install:
  - $CC --version
  - $CXX --version
  - env
  - wget "http://downloads.sourceforge.net/project/boost/boost/1.60.0/boost_1_60_0.tar.bz2" -O /tmp/boost.tbz2

install:
  - . ./install-boost.sh

script:
  - mkdir build; cd build
  - cmake ..
  - make all test
  - find -type f -executable -name 'test-*' | xargs -i% valgrind --error-exitcode=-1 %
