//          Copyright Camille Gillot 2012 - 2014.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)

#undef MMETHOD_TRAMPOLINE_TYPE

#undef MMETHOD_TRAMPOLINE_CALL_ARG
#undef MMETHOD_TRAMPOLINE_CALL_PARM_TYPE
#undef MMETHOD_TRAMPOLINE_CALL_PARM_TYPES
#undef MMETHOD_TRAMPOLINE_CALL_PARM
#undef MMETHOD_TRAMPOLINE_CALL_PARMS

#undef MMETHOD_TRAMPOLINE_FUNC_ARG
#undef MMETHOD_TRAMPOLINE_FUNC_PARM_TYPE
#undef MMETHOD_TRAMPOLINE_FUNC_PARM_TYPES
#undef MMETHOD_TRAMPOLINE_FUNC_PARM
#undef MMETHOD_TRAMPOLINE_FUNC_PARMS
